test_foundation/config/routes.rb
Rails.application.routes.draw do
  resources :movies

  get 'welcome/index'

end

test_foundation/app/models/movie.rb
class Movie < ActiveRecord::Base
end

test_foundation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

test_foundation/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :cast, :genre, :length, :url, :year)
    end
end

test_foundation/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

test_foundation/app/helpers/application_helper.rb
module ApplicationHelper
end

test_foundation/app/helpers/movies_helper.rb
module MoviesHelper
end

test_foundation/app/helpers/welcome_helper.rb
module WelcomeHelper
end

test_foundation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

test_foundation/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cast %><br>
    <%= f.text_area :cast %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

test_foundation/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

test_foundation/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Cast</th>
      <th>Genre</th>
      <th>Length</th>
      <th>Url</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.cast %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.length %></td>
        <td><%= movie.url %></td>
        <td><%= movie.year %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path, class: "button radius" %>

test_foundation/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

test_foundation/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Cast:</strong>
  <%= @movie.cast %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Url:</strong>
  <%= @movie.url %>

  <video width="320" height="240" controls>
    <source src= <%= @movie.url %> type="video/mp4">

      Your browser does not support the video tag.
    </video>
  </p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

test_foundation/app/views/welcome/index.html.erb
<div class="row">
  <div class="large-3 columns">
    <h1><img src="http://placehold.it/400x100&text=Logo"/></h1>
  </div>
  <div class="large-9 columns">
    <ul class="right button-group">
      <li><a href="http://localhost:3000/welcome/index" class="button">Home</a></li>
      <li><a href="http://localhost:3000/movies" class="button">Listing Movies</a></li>
      <li><a href="http://localhost:3000/movies/new" class="button">Add a New Movie</a></li>
      <li><a href="http://localhost:3000/movies/1" class="button">Display the Movie</a></li>
    </ul>
  </div>
</div>





<div class="row">
  <div class="large-12 columns">
    <div id="slider">
      <img src="http://placehold.it/1000x400&text=[ img 1 ]"/>
    </div>

    <hr/>
  </div>
</div>


<div class="row">
  <div class="large-4 columns">
    <img src="http://placehold.it/400x300&text=[img]"/>
    <h4>This is a content section.</h4>
    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
  </div>

  <div class="large-4 columns">
    <img src="http://placehold.it/400x300&text=[img]"/>
    <h4>This is a content section.</h4>
    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
  </div>

  <div class="large-4 columns">
    <img src="http://placehold.it/400x300&text=[img]"/>
    <h4>This is a content section.</h4>
    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
  </div>

</div>


<div class="row">
  <div class="large-12 columns">

    <div class="panel">
      <h4>Get in touch!</h4>

      <div class="row">
        <div class="large-9 columns">
          <p>We'd love to hear from you, you attractive person you.</p>
        </div>
        <div class="large-3 columns">
          <a href="#" class="radius button right">Contact Us</a>
        </div>
      </div>
    </div>

  </div>
</div>



<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="http://localhost:3000/welcome/index" >Home</a></li>
          <li><a href="http://localhost:3000/movies" >Listing Movies</a></li>
          <li><a href="http://localhost:3000/movies/new" >Add a New Movie</a></li>
          <li><a href="http://localhost:3000/movies/1">Display the Movie</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>